from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PUBLIC_DIR = PROJECT_ROOT / "public"

DEFAULT_MP3_DIR = PUBLIC_DIR / "mp3"
DEFAULT_MIDI_DIR = PUBLIC_DIR / "midi"
DEFAULT_FINAL_MP3_DIR = PUBLIC_DIR / "piano_mp3"

N_FFT = 2048
HOP_LENGTH = 512
VELOCITY = 100
THRESHOLD_RATIO = 0.1
NOTE_DURATION = 0.5
MAX_MELODY_FREQ = 3000
MAX_NOTE_JUMP = 24

ENV_MP3_PATH = "PIANO_MP3_PATH"
ENV_MIDI_PATH = "PIANO_OUTPUT_MIDI_PATH"

SOUNDFONT_PATH = PUBLIC_DIR / "soundfont.sf2"